name: Deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build (skip tests)
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push (latest)
        run: |
          docker build -t sungminju/chicchic:latest .
          docker push sungminju/chicchic:latest

      - name: Deploy on EC2 (create .env, pull & restart)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ELASTIC_IP }}
          username: ubuntu
          key: ${{ secrets.PEM_KEY }}
          script: |
            set -e
            mkdir -p ~/app
            cd ~/app

            # .env 생성 (GitHub Secrets 값 사용)
            cat > .env <<'EOF'
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
            NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            cloud.aws.credentials.accessKey=${{ secrets.AWS_ACCESS_KEY }}
            cloud.aws.credentials.secretKey=${{ secrets.AWS_SECRET_KEY }}
            cloud.aws.region.static=${{ secrets.AWS_REGION }}
            cloud.aws.s3.bucket=${{ secrets.AWS_BUCKET }}
            EOF

            # 최신 이미지 가져와서 컨테이너 교체 실행
            sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            sudo docker pull sungminju/chicchic:latest
            sudo docker compose up -d --remove-orphans || sudo docker-compose -p chicchic up -d --remove-orphans

            # 안 쓰는 오래된 이미지 정리
            sudo docker image prune -af --filter "until=24h"
